//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 WindowCustomizeTool.rc 使用
//
#define IDI_ICON_SELECTOR               1201
#define IDI_ICON_SELECTOR_FILLED        1202
#define IDI_ICON_SELECTOR_16x16         1203
#define IDC_CURSOR_WINSELECT            1301
#define IDD_DIALOG_ABOUT                1501
#define IDD_DIALOG_WINDOWFINDER1        1502
#define IDD_DIALOG_SWP_ARGS             1503
#define IDR_MENU_MAINWND                1601
#define IDR_ACCELERATOR_MAINWND         1602
#define IDC_WINDOWFINDER_CAPTION        1623
#define IDC_WINDOWFINDER_CLASS          1624
#define IDC_WINDOWFINDER_HANDLE         1625
#define IDC_WINDOWFINDER_FT             1626
#define IDC_EDIT_SWP_hWndInsertAfter    1627
#define IDC_EDIT_SWP_X                  1628
#define IDC_EDIT_SWP_Y                  1629
#define IDC_EDIT_SWP_cx                 1630
#define IDC_EDIT_SWP_cy                 1631
#define IDC_EDIT_SWP_uFlags             1632
#define IDC_BUTTON_SWP_APPLY            1633
#define IDC_BUTTON_SWP_HELP             1634
#define ID_MENU_FILE_CLOSE              32774
#define ID_MENU_FILE_EXIT               32775
#define ID_MENU_FILE_NEW                32776
#define ID_MENU_FILE_SAVE_WINDOWLIST    32777
#define ID_MENU_FILE_SAVE_HWNDLIST      32778
#define ID_MENU_EDIT_OPTIONS            32779
#define ID_MENU_WINDOW_NEW              32780
#define ID_MENU_OPTIONS_SETTINGS        32781
#define ID_MENU_OPTIONS_ALWAYSONTOP     32782
#define ID_MENU_OPTIONS_TASKBARICON     32783
#define ID_MENU_HELP_ABOUT              32784
#define ID_MENU_HELP_HELP               32785
#define ID_MENU_OPTIONS_HIDEWHENMINIMID 32786
#define ID_MENU_WINDOW_FIND             32787
#define ID_MENU_WINDOWMANAGER_BTF       32788
#define ID_MENU_WINDOWMANAGER_SWITCHTO  32789
#define ID_MENU_NEW_FRAME_MAINWND       32790
#define ID_MENU_PROCESS_IMAGENAME       32791
#define ID_MENU_PROCESS_PID             32792
#define ID_MENU_PROCESS_TERMINATE       32793
#define ID_MENU_PROCESS_OPENLOCATION    32794
#define ID_MENU_PROCESS_KILLANDDELETE   32795
#define ID_MENU_WINDOWMANAGER_PROPERIES 32796
#define ID_MENU_WINDOWMANAGER_MAXIMIZE  32802
#define ID_MENU_WINDOWMANAGER_MINIMIZE  32803
#define ID_MENU_WINDOWMANAGER_HIDE      32804
#define ID_MENU_WINDOWMANAGER_SHOW      32805
#define ID_MENU_WINDOWMANAGER_RELOAD    32806
#define ID_MENU_WINDOWMANAGER_SWP       32807
#define ID_MENU_WINDOWMANAGER_ENDTASK   32808
#define ID_MENU_WINDOWMANAGER_DESTROY   32809
#define ID_MENU_WINDOWMANAGER_CLOSE     32810
#define ID_MENU_ABOUT                   32812
#define ID_MENU_WINDOWMANAGER_RESIZE    32813
#define ID_MENU_PROCESS_IMAGEPATH       32814
#define ID_MENU_WINDOWMANAGER_HIGHLIGHT 32816
#define ID_MENU_WINDOWMANAGER_SENDMESSAGE 32817
#define ID_MENU_EDIT_CUT                32818
#define ID_MENU_EDIT_COPY               32819
#define ID_MENU_EDIT_PASTE              32820
#define ID_MENU_EDIT_SELECTALL          32821
#define ID_MENU_FILE_INSTANCES          32822
#define ID_MENU_OPTIONS_PUT_BUTTOM_WHEN_USE 32823
#define ID_MENU_OPTIONS_SHOWFORMAT      32824
#define ID_MENU_OPTIONS_SHOWFORMAT_DEC  32825
#define ID_MENU_OPTIONS_SHOWFORMAT_HEX  32826
#define ID_MENU_FILE_CLOSE_TOTALLY      32827
#define ID_MENU_FILE_INSTALL_APP        32828
#define ID_MENU_OPTIONS_WLPREF_HELP     32829
#define ID_MENU_OPTIONS_WLPREF_CONTROLS 32830
#define ID_MENU_OPTIONS_WLPREF_TOPLEVEL 32831
#define ID_MENU_OPTIONS_WLPREF_ROOTOWNER 32832
#define ID_MENU_OPTIONS_AUTOREFRESH     32833
#define ID_MENU_VIEW_MAINWINDOW_ALPHA        32834
#define ID_MENU_VIEW_MAINWINDOW_CORNER_0     32835
#define ID_MENU_VIEW_MAINWINDOW_CORNER_1     32836
#define ID_MENU_VIEW_MAINWINDOW_CORNER_2     32837
#define ID_MENU_VIEW_MAINWINDOW_CORNER_3     32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1801
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1636
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
